// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: konemwiremessage.proto
package konem.data.protobuf

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.WireField
import com.squareup.wire.internal.missingRequiredFields
import okio.ByteString
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Nothing
import kotlin.String
import kotlin.jvm.JvmField

class Data(
    @field:WireField(
        tag = 1,
        adapter = "com.squareup.wire.ProtoAdapter#STRING",
        label = WireField.Label.REQUIRED
    )
    val data: String,
    unknownFields: ByteString = ByteString.EMPTY
) : Message<Data, Nothing>(ADAPTER, unknownFields) {
    @Deprecated(
        message = "Shouldn't be used in Kotlin",
        level = DeprecationLevel.HIDDEN
    )
    override fun newBuilder(): Nothing = throw AssertionError()

    override fun equals(other: Any?): Boolean {
        if (other === this) return true
        if (other !is Data) return false
        return unknownFields == other.unknownFields &&
            data == other.data
    }

    override fun hashCode(): Int {
        var result = super.hashCode
        if (result == 0) {
            result = unknownFields.hashCode()
            result = result * 37 + data.hashCode()
            super.hashCode = result
        }
        return result
    }

    override fun toString(): String {
        val result = mutableListOf<String>()
        result += """data=$data"""
        return result.joinToString(prefix = "Data{", separator = ", ", postfix = "}")
    }

    fun copy(data: String = this.data, unknownFields: ByteString = this.unknownFields): Data =
        Data(data, unknownFields)

    companion object {
        @JvmField
        val ADAPTER: ProtoAdapter<Data> = object : ProtoAdapter<Data>(
            FieldEncoding.LENGTH_DELIMITED,
            Data::class
        ) {
            override fun encodedSize(value: Data): Int =
                ProtoAdapter.STRING.encodedSizeWithTag(1, value.data) +
                    value.unknownFields.size

            override fun encode(writer: ProtoWriter, value: Data) {
                ProtoAdapter.STRING.encodeWithTag(writer, 1, value.data)
                writer.writeBytes(value.unknownFields)
            }

            override fun decode(reader: ProtoReader): Data {
                var data: String? = null
                val unknownFields = reader.forEachTag { tag ->
                    when (tag) {
                        1 -> data = ProtoAdapter.STRING.decode(reader)
                        else -> reader.readUnknownField(tag)
                    }
                }
                return Data(
                    data = data ?: throw missingRequiredFields(data, "data"),
                    unknownFields = unknownFields
                )
            }

            override fun redact(value: Data): Data = value.copy(
                unknownFields = ByteString.EMPTY
            )
        }
    }
}
