// Code generated by Wire protocol buffer compiler, do not edit.
// Source: konem.data.protobuf.Data in konemwiremessage.proto
package konem.`data`.protobuf

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_2
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.missingRequiredFields
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import okio.ByteString

public class Data(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REQUIRED,
    declaredName = "data",
    schemaIndex = 0,
  )
  public val data_: String,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<Data, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is Data) return false
    if (unknownFields != other.unknownFields) return false
    if (data_ != other.data_) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + data_.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """data_=${sanitize(data_)}"""
    return result.joinToString(prefix = "Data{", separator = ", ", postfix = "}")
  }

  public fun copy(data_: String = this.data_, unknownFields: ByteString = this.unknownFields): Data
      = Data(data_, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<Data> = object : ProtoAdapter<Data>(
      FieldEncoding.LENGTH_DELIMITED, 
      Data::class, 
      "type.googleapis.com/konem.data.protobuf.Data", 
      PROTO_2, 
      null, 
      "konemwiremessage.proto"
    ) {
      override fun encodedSize(`value`: Data): Int {
        var size = value.unknownFields.size
        size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.data_)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: Data) {
        ProtoAdapter.STRING.encodeWithTag(writer, 1, value.data_)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: Data) {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.STRING.encodeWithTag(writer, 1, value.data_)
      }

      override fun decode(reader: ProtoReader): Data {
        var data_: String? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> data_ = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return Data(
          data_ = data_ ?: throw missingRequiredFields(data_, "data"),
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: Data): Data = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
