// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: konemwiremessage.proto
package konem.data.protobuf

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.WireField
import com.squareup.wire.internal.missingRequiredFields
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Nothing
import kotlin.String
import kotlin.jvm.JvmField
import okio.ByteString

class HeartBeat(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REQUIRED
  )
  val time: String,
  unknownFields: ByteString = ByteString.EMPTY
) : Message<HeartBeat, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is HeartBeat) return false
    return unknownFields == other.unknownFields
        && time == other.time
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + time.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """time=$time"""
    return result.joinToString(prefix = "HeartBeat{", separator = ", ", postfix = "}")
  }

  fun copy(time: String = this.time, unknownFields: ByteString = this.unknownFields): HeartBeat =
      HeartBeat(time, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<HeartBeat> = object : ProtoAdapter<HeartBeat>(
      FieldEncoding.LENGTH_DELIMITED, 
      HeartBeat::class
    ) {
      override fun encodedSize(value: HeartBeat): Int = 
        ProtoAdapter.STRING.encodedSizeWithTag(1, value.time) +
        value.unknownFields.size

      override fun encode(writer: ProtoWriter, value: HeartBeat) {
        ProtoAdapter.STRING.encodeWithTag(writer, 1, value.time)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): HeartBeat {
        var time: String? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> time = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return HeartBeat(
          time = time ?: throw missingRequiredFields(time, "time"),
          unknownFields = unknownFields
        )
      }

      override fun redact(value: HeartBeat): HeartBeat = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }
  }
}
