// Code generated by Wire protocol buffer compiler, do not edit.
// Source: konem.data.protobuf.HeartBeat in konemwiremessage.proto
package konem.`data`.protobuf

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_2
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.missingRequiredFields
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Unit
import kotlin.jvm.JvmField
import okio.ByteString

public class HeartBeat(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REQUIRED,
  )
  public val time: String,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<HeartBeat, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  public override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is HeartBeat) return false
    if (unknownFields != other.unknownFields) return false
    if (time != other.time) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + time.hashCode()
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    result += """time=${sanitize(time)}"""
    return result.joinToString(prefix = "HeartBeat{", separator = ", ", postfix = "}")
  }

  public fun copy(time: String = this.time, unknownFields: ByteString = this.unknownFields):
      HeartBeat = HeartBeat(time, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<HeartBeat> = object : ProtoAdapter<HeartBeat>(
      FieldEncoding.LENGTH_DELIMITED, 
      HeartBeat::class, 
      "type.googleapis.com/konem.data.protobuf.HeartBeat", 
      PROTO_2, 
      null, 
      "konemwiremessage.proto"
    ) {
      public override fun encodedSize(`value`: HeartBeat): Int {
        var size = value.unknownFields.size
        size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.time)
        return size
      }

      public override fun encode(writer: ProtoWriter, `value`: HeartBeat): Unit {
        ProtoAdapter.STRING.encodeWithTag(writer, 1, value.time)
        writer.writeBytes(value.unknownFields)
      }

      public override fun encode(writer: ReverseProtoWriter, `value`: HeartBeat): Unit {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.STRING.encodeWithTag(writer, 1, value.time)
      }

      public override fun decode(reader: ProtoReader): HeartBeat {
        var time: String? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> time = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return HeartBeat(
          time = time ?: throw missingRequiredFields(time, "time"),
          unknownFields = unknownFields
        )
      }

      public override fun redact(`value`: HeartBeat): HeartBeat = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
