// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: konemwiremessage.proto
package konem.data.protobuf

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.WireField
import com.squareup.wire.internal.missingRequiredFields
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Nothing
import kotlin.String
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

class KonemMessage(
  @field:WireField(
    tag = 1,
    adapter = "konem.data.protobuf.MessageType#ADAPTER",
    label = WireField.Label.REQUIRED
  )
  val messageType: MessageType,
  @field:WireField(
    tag = 2,
    adapter = "konem.data.protobuf.Unknown#ADAPTER"
  )
  val unknown: Unknown? = null,
  @field:WireField(
    tag = 3,
    adapter = "konem.data.protobuf.Status#ADAPTER"
  )
  val status: Status? = null,
  @field:WireField(
    tag = 4,
    adapter = "konem.data.protobuf.HeartBeat#ADAPTER"
  )
  val heartBeat: HeartBeat? = null,
  @field:WireField(
    tag = 5,
    adapter = "konem.data.protobuf.Data#ADAPTER"
  )
  val data: Data? = null,
  unknownFields: ByteString = ByteString.EMPTY
) : Message<KonemMessage, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is KonemMessage) return false
    return unknownFields == other.unknownFields
        && messageType == other.messageType
        && unknown == other.unknown
        && status == other.status
        && heartBeat == other.heartBeat
        && data == other.data
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + messageType.hashCode()
      result = result * 37 + unknown.hashCode()
      result = result * 37 + status.hashCode()
      result = result * 37 + heartBeat.hashCode()
      result = result * 37 + data.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """messageType=$messageType"""
    if (unknown != null) result += """unknown=$unknown"""
    if (status != null) result += """status=$status"""
    if (heartBeat != null) result += """heartBeat=$heartBeat"""
    if (data != null) result += """data=$data"""
    return result.joinToString(prefix = "KonemMessage{", separator = ", ", postfix = "}")
  }

  fun copy(
    messageType: MessageType = this.messageType,
    unknown: Unknown? = this.unknown,
    status: Status? = this.status,
    heartBeat: HeartBeat? = this.heartBeat,
    data: Data? = this.data,
    unknownFields: ByteString = this.unknownFields
  ): KonemMessage = KonemMessage(messageType, unknown, status, heartBeat, data, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<KonemMessage> = object : ProtoAdapter<KonemMessage>(
      FieldEncoding.LENGTH_DELIMITED, 
      KonemMessage::class
    ) {
      override fun encodedSize(value: KonemMessage): Int = 
        MessageType.ADAPTER.encodedSizeWithTag(1, value.messageType) +
        Unknown.ADAPTER.encodedSizeWithTag(2, value.unknown) +
        Status.ADAPTER.encodedSizeWithTag(3, value.status) +
        HeartBeat.ADAPTER.encodedSizeWithTag(4, value.heartBeat) +
        Data.ADAPTER.encodedSizeWithTag(5, value.data) +
        value.unknownFields.size

      override fun encode(writer: ProtoWriter, value: KonemMessage) {
        MessageType.ADAPTER.encodeWithTag(writer, 1, value.messageType)
        Unknown.ADAPTER.encodeWithTag(writer, 2, value.unknown)
        Status.ADAPTER.encodeWithTag(writer, 3, value.status)
        HeartBeat.ADAPTER.encodeWithTag(writer, 4, value.heartBeat)
        Data.ADAPTER.encodeWithTag(writer, 5, value.data)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): KonemMessage {
        var messageType: MessageType? = null
        var unknown: Unknown? = null
        var status: Status? = null
        var heartBeat: HeartBeat? = null
        var data: Data? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> messageType = MessageType.ADAPTER.decode(reader)
            2 -> unknown = Unknown.ADAPTER.decode(reader)
            3 -> status = Status.ADAPTER.decode(reader)
            4 -> heartBeat = HeartBeat.ADAPTER.decode(reader)
            5 -> data = Data.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return KonemMessage(
          messageType = messageType ?: throw missingRequiredFields(messageType, "messageType"),
          unknown = unknown,
          status = status,
          heartBeat = heartBeat,
          data = data,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: KonemMessage): KonemMessage = value.copy(
        unknown = value.unknown?.let(Unknown.ADAPTER::redact),
        status = value.status?.let(Status.ADAPTER::redact),
        heartBeat = value.heartBeat?.let(HeartBeat.ADAPTER::redact),
        data = value.data?.let(Data.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }
  }
}
