// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: konemwiremessage.proto
package konem.data.protobuf

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.WireEnum
import kotlin.Int
import kotlin.jvm.JvmField
import kotlin.jvm.JvmStatic

enum class MessageType(
    override val value: Int
) : WireEnum {
    UNKNOWN(0),

    STATUS(1),

    HEARTBEAT(2),

    DATA(3);

    companion object {
        @JvmField
        val ADAPTER: ProtoAdapter<MessageType> = object : EnumAdapter<MessageType>(
            MessageType::class
        ) {
            override fun fromValue(value: Int): MessageType? = MessageType.fromValue(value)
        }

        @JvmStatic
        fun fromValue(value: Int): MessageType? = when (value) {
            0 -> UNKNOWN
            1 -> STATUS
            2 -> HEARTBEAT
            3 -> DATA
            else -> null
        }
    }
}
