// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: konemwiremessage.proto
package konem.data.protobuf

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.WireField
import com.squareup.wire.internal.missingRequiredFields
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Nothing
import kotlin.String
import kotlin.jvm.JvmField
import okio.ByteString

class Status(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REQUIRED
  )
  val shortName: String,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.REQUIRED
  )
  val errors: Int,
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.REQUIRED
  )
  val received: Int,
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.REQUIRED
  )
  val sent: Int,
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REQUIRED
  )
  val description: String,
  unknownFields: ByteString = ByteString.EMPTY
) : Message<Status, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is Status) return false
    return unknownFields == other.unknownFields
        && shortName == other.shortName
        && errors == other.errors
        && received == other.received
        && sent == other.sent
        && description == other.description
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + shortName.hashCode()
      result = result * 37 + errors.hashCode()
      result = result * 37 + received.hashCode()
      result = result * 37 + sent.hashCode()
      result = result * 37 + description.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """shortName=$shortName"""
    result += """errors=$errors"""
    result += """received=$received"""
    result += """sent=$sent"""
    result += """description=$description"""
    return result.joinToString(prefix = "Status{", separator = ", ", postfix = "}")
  }

  fun copy(
    shortName: String = this.shortName,
    errors: Int = this.errors,
    received: Int = this.received,
    sent: Int = this.sent,
    description: String = this.description,
    unknownFields: ByteString = this.unknownFields
  ): Status = Status(shortName, errors, received, sent, description, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<Status> = object : ProtoAdapter<Status>(
      FieldEncoding.LENGTH_DELIMITED, 
      Status::class
    ) {
      override fun encodedSize(value: Status): Int = 
        ProtoAdapter.STRING.encodedSizeWithTag(1, value.shortName) +
        ProtoAdapter.INT32.encodedSizeWithTag(2, value.errors) +
        ProtoAdapter.INT32.encodedSizeWithTag(3, value.received) +
        ProtoAdapter.INT32.encodedSizeWithTag(4, value.sent) +
        ProtoAdapter.STRING.encodedSizeWithTag(5, value.description) +
        value.unknownFields.size

      override fun encode(writer: ProtoWriter, value: Status) {
        ProtoAdapter.STRING.encodeWithTag(writer, 1, value.shortName)
        ProtoAdapter.INT32.encodeWithTag(writer, 2, value.errors)
        ProtoAdapter.INT32.encodeWithTag(writer, 3, value.received)
        ProtoAdapter.INT32.encodeWithTag(writer, 4, value.sent)
        ProtoAdapter.STRING.encodeWithTag(writer, 5, value.description)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): Status {
        var shortName: String? = null
        var errors: Int? = null
        var received: Int? = null
        var sent: Int? = null
        var description: String? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> shortName = ProtoAdapter.STRING.decode(reader)
            2 -> errors = ProtoAdapter.INT32.decode(reader)
            3 -> received = ProtoAdapter.INT32.decode(reader)
            4 -> sent = ProtoAdapter.INT32.decode(reader)
            5 -> description = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return Status(
          shortName = shortName ?: throw missingRequiredFields(shortName, "shortName"),
          errors = errors ?: throw missingRequiredFields(errors, "errors"),
          received = received ?: throw missingRequiredFields(received, "received"),
          sent = sent ?: throw missingRequiredFields(sent, "sent"),
          description = description ?: throw missingRequiredFields(description, "description"),
          unknownFields = unknownFields
        )
      }

      override fun redact(value: Status): Status = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }
  }
}
