// Code generated by Wire protocol buffer compiler, do not edit.
// Source: konem.data.protobuf.Unknown in konemwiremessage.proto
package konem.`data`.protobuf

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_2
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.missingRequiredFields
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import okio.ByteString

public class Unknown(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REQUIRED,
    schemaIndex = 0,
  )
  public val unknown: String,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<Unknown, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is Unknown) return false
    if (unknownFields != other.unknownFields) return false
    if (unknown != other.unknown) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + unknown.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """unknown=${sanitize(unknown)}"""
    return result.joinToString(prefix = "Unknown{", separator = ", ", postfix = "}")
  }

  public fun copy(unknown: String = this.unknown, unknownFields: ByteString = this.unknownFields):
      Unknown = Unknown(unknown, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<Unknown> = object : ProtoAdapter<Unknown>(
      FieldEncoding.LENGTH_DELIMITED, 
      Unknown::class, 
      "type.googleapis.com/konem.data.protobuf.Unknown", 
      PROTO_2, 
      null, 
      "konemwiremessage.proto"
    ) {
      override fun encodedSize(`value`: Unknown): Int {
        var size = value.unknownFields.size
        size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.unknown)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: Unknown) {
        ProtoAdapter.STRING.encodeWithTag(writer, 1, value.unknown)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: Unknown) {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.STRING.encodeWithTag(writer, 1, value.unknown)
      }

      override fun decode(reader: ProtoReader): Unknown {
        var unknown: String? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> unknown = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return Unknown(
          unknown = unknown ?: throw missingRequiredFields(unknown, "unknown"),
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: Unknown): Unknown = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
